# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e8eb98319ef01f982abd51890dd0b62e3fec0044a8dedc79d3119ea86f760e31694cfc4659c6c853e191ee5dd50c6bfb707a73658d84b6dac497e7e039eba95

test:
  secret_key_base: 95d7389388f54ca498f14dcfacd27e46c83ada66ff61c59c60e0846b9a0885d73c01ecfc065ed15b56fe7fc6332a5b11c63683df8cc684a725cff7a40893646a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
